# This file was generated by GoReleaser. DO NOT EDIT.
class Configurd < Formula
  desc "CLI utility manage infrastructure as code with helm"
  homepage "https://github.com/foomo/configurd"
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/foomo/configurd/releases/download/0.0.3/configurd_0.0.3_darwin_amd64.tar.gz"
    sha256 "2a504499c975534389a7e892652fb4f085ca2c0b5e7769fa0ddc1217a368f8f8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/foomo/configurd/releases/download/0.0.3/configurd_0.0.3_linux_amd64.tar.gz"
      sha256 "fbae5e2f44bf52d06afd1763c0bbc5787447fc0ae2ca33817a563d5caf4dee4b"
    end
  end

  def install
    bin.install "configurd"
  end

  def caveats; <<~EOS
    configurd -h
  EOS
  end
end
