# This file was generated by GoReleaser. DO NOT EDIT.
class Configurd < Formula
  desc "CLI utility manage infrastructure as code with helm"
  homepage "https://github.com/foomo/configurd"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/foomo/configurd/releases/download/0.2.0/configurd_0.2.0_darwin_amd64.tar.gz"
    sha256 "3b527759c33f54f749966e1891e836fa65a4f4132dd50eed7ca6f1b728317afc"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/foomo/configurd/releases/download/0.2.0/configurd_0.2.0_linux_amd64.tar.gz"
      sha256 "7f4ff57bb568e670eeb01bee7f79e59d86240f24615b447421e7e2151b6e5528"
    end
  end

  def install
    bin.install "configurd"
  end

  def caveats; <<~EOS
    configurd -h
  EOS
  end
end
