# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Squadron < Formula
  desc "CLI utility manage infrastructure as code with helm"
  homepage "https://github.com/foomo/squadron"
  version "2.0.0-rc.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/foomo/squadron/releases/download/v2.0.0-rc.1/squadron_2.0.0-rc.1_darwin_arm64.tar.gz"
      sha256 "cd81656871097b7d129579fddc5705b928f93fbf702af59a1ea964f7dff06488"

      def install
        bin.install "squadron"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/foomo/squadron/releases/download/v2.0.0-rc.1/squadron_2.0.0-rc.1_darwin_amd64.tar.gz"
      sha256 "e9c18641fe0c9e2c155fce04aad6fe812215f60eaaef0d82b55609eb97352551"

      def install
        bin.install "squadron"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/squadron/releases/download/v2.0.0-rc.1/squadron_2.0.0-rc.1_linux_amd64.tar.gz"
      sha256 "7078dc35ffeb2e7148fe46cbee07fed8018bc2a2167cd2edc84eb206e59ca900"

      def install
        bin.install "squadron"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/squadron/releases/download/v2.0.0-rc.1/squadron_2.0.0-rc.1_linux_arm64.tar.gz"
      sha256 "3c7607b862f5fc8827a5212f7298cf4e56df296a7760ee48ebc0e939094ec9f4"

      def install
        bin.install "squadron"
      end
    end
  end

  def caveats
    <<~EOS
      squadron -h
    EOS
  end
end
